CREATE TABLE IF NOT EXISTS drg_seeds (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	game_version TEXT NOT NULL,
	seed_g INTEGER NOT NULL,
	seed_m INTEGER NOT NULL,
	seed_p INTEGER NOT NULL,
	season TEXT NOT NULL,
	primary_obj TEXT NOT NULL,
	secondary_obj TEXT NOT NULL,
	complexity INTEGER CHECK (complexity BETWEEN 1 AND 3),
	length INTEGER CHECK (length BETWEEN 1 AND 3),
	machine_event TEXT,
	data_cell INTEGER CHECK (data_cell BETWEEN 0 AND 1),
	core_stone INTEGER CHECK (core_stone BETWEEN 0 AND 1),
	plagueheart INTEGER CHECK (plagueheart >= 0),
	huuli_hoarder BOOLEAN DEFAULT 0,
	tyrant_weed BOOLEAN DEFAULT 0,
	crassus_detonator BOOLEAN DEFAULT 0,
	err_cube BOOLEAN DEFAULT 0,
	bittergem BOOLEAN DEFAULT 0,
	date_added DATETIME DEFAULT CURRENT_TIMESTAMP,
	date_modified DATETIME DEFAULT CURRENT_TIMESTAMP,
	notes TEXT,
	UNIQUE(seed_g, seed_m, seed_p, season)
);